# Generated by Django 6.0.3 on 2026-03-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_event_fecha_creacion_event_foto_event_lugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clubes/'),
        ),
    ]
