# Generated by Django 6.0.3 on 2026-03-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='color',
            field=models.CharField(default='#dc3545', help_text='Color en formato hexadecimal, ej: #dc3545', max_length=7),
        ),
    ]
